### ISSUE TITLE
建议：文档转Markdown或者Asciidoc, 这样可以在github上面，吸引大家加入贡献

### ISSUE THREAD

**Issue by ghost** [loongson-community/docs#1]
建议：文档转Markdown或者Asciidoc, 这样可以在github上面，吸引大家加入贡献

本质上PDF, 是无法用git等版本管理工具来控制版本，比对差异diff的。

而Markdown或者Asciidoc，是文本，所以可以用git工具管理版本。

社区想要加入贡献，PDF不容易入手。

建议转换一下。

另外，从Markdown和Asciidoc转换pdf，也是有现成的方案

**Comment by FlyGoat** [comment]
我们暂时没有条件代替龙芯编写文档:-(

**Comment by lshw** [comment]
可以从Loongarch文档开始试试，逆向文档

**Comment by MariaBombardier** [comment]
以后搞个github page再说吧（
